name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
      - name: Checkout
        uses: actions/checkout@v3
      # Cleanup The Actions Workspace Using Custom Composite Run Actio
      
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.time.outputs.time }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: master
          draft: false
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    # You might want to Checkout your repo first, but not mandatory
    needs: prepare_release
    strategy:
      matrix:
        BOARD: [xiaomi-umi]
        DISTRO: [armbian]
        FLAVOR: [ubuntu]
        BRANCH: [sm8250]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload Armbian image
        uses: amazingfate/armbian-compile-action@main
        if: matrix.DISTRO == 'armbian'
        with:
          branch: ${{ matrix.BRANCH }}
          board: ${{ matrix.BOARD }}
          flavor: ${{ matrix.FLAVOR }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
